import { expect, it } from 'vitest'
import { tutorialSteps } from './tutorial-catalog'

// Owner-approved copy from the consolidated post-promotion 25B mission.
const ownerCopy = [
  {"id":"profile","title":"Profil","text":"Avatar, pseudo, niveau et élément. Cliquez pour ouvrir les détails de votre Profil."},
  {"id":"resources","title":"Ressources","text":"Vos Primos, Moras et particules, avec des raccourcis contextuels."},
  {"id":"active-team","title":"Équipe active","text":"Voici la Team actuellement utilisée."},
  {"id":"objective","title":"Objectif actuel","text":"Retrouvez votre cible d’invocation et ses principales informations."},
  {"id":"daily-tracker","title":"Quotidiennes","text":"Parcourez les rappels et accédez aux activités du jour."},
  {"id":"main-navigation","title":"Navigation principale","text":"Accueil, Invocation, Personnages, Activités, Sac, Boutique et Configuration : vos destinations principales."},
  {"id":"home","title":"Accueil","text":"La bannière mène à Invocation. Quotidiennes résume ce qu’il reste à faire."},
  {"id":"community","title":"Communauté","text":"Retrouvez ici le Chat global et les Messages privés."},
  {"id":"menu-entry","title":"Menu","text":"Le Menu donne accès aux autres destinations joueurs. Retrouvez aussi le Tutoriel ici pour reprendre ou le recommencer entièrement."},
  {"id":"menu-destinations","title":"Destinations","text":"Parcourez les pages du Menu pour trouver votre destination. Configuration permet de personnaliser leur ordre et leur visibilité."},
  {"id":"notifications-entry","title":"Notifications","text":"Ce bouton regroupe les nouveautés et les rappels de votre compte."},
  {"id":"notifications-panel","title":"Rappels et raccourcis","text":"Les lignes indiquent leur état et leurs éventuels raccourcis. La visite ne les marque pas lues et ne les archive pas."},
  {"id":"invocation-banner","title":"Bannière et rotation","text":"Retrouvez la cible de la rotation et sa date de fin. Sans cible, le sélecteur présente les personnages disponibles."},
  {"id":"invocation-target","title":"Changer de cible","text":"Changer ouvre les cibles de la rotation. Votre sélection reste inchangée pendant cette visite."},
  {"id":"invocation-characters","title":"Personnages 4★","text":"Personnages 4★ de la rotation actuelle. Vous pouvez les obtenir en invoquant sur la bannière du personnage 5★."},
  {"id":"invocation-progress","title":"Pity, Garantie et Capture","text":"Ces indicateurs suivent votre progression d’Invocation et sont conservés entre les rotations. Consultez Détail pour les règles disponibles."},
  {"id":"invocation-actions","title":"Invocation x1 ou x10","text":"Chaque bouton indique son coût en Primos. Une Invocation dépense vos ressources."},
  {"id":"invocation-detail","title":"Détail des Invocations","text":"Consultez les probabilités, les passifs et l’historique disponibles dans Détail."},
  {"id":"box-filters","title":"Votre Box","text":"La Box contient vos personnages possédés. Recherche, rareté, élément, constellation et tri permettent de les retrouver."},
  {"id":"box-possessions","title":"Possessions et états","text":"Les cartes indiquent rareté, constellation et états utiles. Les favoris facilitent votre organisation."},
  {"id":"box-character","title":"Fiche personnage","text":"La fiche rassemble les informations de votre personnage, comme ses constellations et ses états Combat ou Expédition."},
  {"id":"box-stella","title":"Stella et constellations","text":"Cette zone indique les Stella disponibles et leur utilisation possible."},
  {"id":"box-expedition","title":"Expédition","text":"La fiche permet de partir, suivre une Expédition puis récupérer son résultat selon l’état affiché."},
  {"id":"team-selection","title":"Équipes et pagination","text":"Parcourez vos équipes avec le sélecteur et ses pages. Consulter une équipe ne la rend pas active."},
  {"id":"team-management","title":"Vider son équipe","text":"Vous pouvez vider les emplacements d’une équipe pour en façonner une nouvelle."},
  {"id":"team-composition","title":"Quatre emplacements","text":"Composez normalement votre équipe dans ces emplacements."},
  {"id":"team-passives","title":"Bonus et passifs","text":"Les passifs dépendent de la composition consultée. La référence explique leurs effets et met en évidence ceux de la formation actuelle."},
  {"id":"catalog-filters","title":"Catalogue des personnages","text":"Ce catalogue présente les personnages du jeu, indépendamment de vos possessions. Utilisez recherche, rareté, élément et tri."},
  {"id":"catalog-votes","title":"Votes de bannière","text":"Vous pouvez voter pour le prochain personnage que vous souhaiteriez voir en bannière. Un vote est définitif pour la semaine."},
  {"id":"dailies-overview","title":"Aperçu quotidien","text":"L’Aperçu rassemble les neuf activités quotidiennes et leurs états réels."},
  {"id":"dailies-wheel","title":"Roue quotidienne","text":"Cette zone présente la Roue, sa disponibilité et son résultat éventuel."},
  {"id":"dailies-challenge","title":"Défi quotidien","text":"Le Défi affiche son objectif, sa progression et ses récompenses une fois attribué. Vous pouvez changer de défi en échange de Moras."},
  {"id":"missions-ranks","title":"Rangs des Missions","text":"Il existe différentes missions permanentes, disponibles par ordre de difficulté : B, A, S et Z."},
  {"id":"missions-progress","title":"Objectifs permanents","text":"Les Missions indiquent progression, récompenses et complétions réelles."},
  {"id":"missions-secret-z","title":"Rang Z","text":"Le rang Z reste verrouillé tant que les objectifs des autres missions n’ont pas été accomplis."},
  {"id":"combat-enemies","title":"Entraînement","text":"Les ennemis et leurs affinités caractérisent la rencontre du jour."},
  {"id":"combat-formation","title":"Formation Combat","text":"La formation Combat est distincte de votre équipe active. Une sélection manuelle ou automatique est disponible."},
  {"id":"combat-preview","title":"Chance de victoire","text":"Vos chances de victoire dépendent de votre formation. Le détail explique le calcul pour déterminer vos chances."},
  {"id":"combat-action","title":"Tentative quotidienne","text":"Combattre utilise une tentative, vous octroie des récompenses en cas de victoire ou met vos personnages vaincus au statut K.O."},
  {"id":"boss-identity","title":"Boss mensuel","text":"Le Boss mensuel affiche son identité, le mois, ses PV et sa résistance. Un Boss vaincu octroie des récompenses."},
  {"id":"boss-formation","title":"Formation et attaque","text":"Sélectionnez votre formation pour vous préparer au combat et déterminer les dégâts prévus."},
  {"id":"boss-action","title":"Dégâts prévus et attaque","text":"Attaquer inflige des dégâts au boss. Chaque joueur peut lui infliger des dégâts à son tour quotidiennement."},
  {"id":"boss-bilan","title":"Contribution au Boss","text":"Bilan présente votre contribution, les participants et les records réellement disponibles. Un Boss vaincu conserve son bilan et ses récompenses enregistrées."},
  {"id":"boss-stats","title":"Statistiques Boss","text":"Retrouvez vos dégâts, attaques, participations, récompenses et records cumulés."},
  {"id":"boss-history","title":"Historique des Boss","text":"Les Boss archivés conservent leurs contributions et statistiques disponibles."},
  {"id":"event-general","title":"Édition et participation","text":"Général présente l’édition réelle, ses dates et votre participation. C’est ici que vous pouvez vous inscrire à l’événement du mois."},
  {"id":"event-bonuses","title":"Points et monnaie","text":"Retrouvez ici vos ressources de l’édition en cours."},
  {"id":"event-daily-bonus","title":"Bonus quotidien du Festival","text":"Un bonus journalier est disponible, n’oubliez pas de le récupérer."},
  {"id":"event-milestones","title":"Paliers du Festival","text":"Cette progression présente les seuils, les récompenses et les paliers déjà atteints."},
  {"id":"event-game-a","title":"Premier jeu","text":"Tentez votre chance pour récupérer la récompense."},
  {"id":"event-game-b","title":"Deuxième jeu","text":"Trouvez la combinaison gagnante."},
  {"id":"event-game-c","title":"Troisième jeu","text":"Envoyez un mot à un joueur."},
  {"id":"event-shop","title":"Shop de l’Événement","text":"Les conversions et l’objet Collection dépendent de l’édition et de vos stocks."},
  {"id":"event-ranking","title":"Classement de l’édition","text":"Ce classement compare les joueurs de l’édition. Il se distingue de vos points personnels."},
  {"id":"arcade-memory","title":"Memory","text":"Memory consiste à retrouver les paires de portraits. Choisissez normalement jeu et difficulté."},
  {"id":"arcade-connect-four","title":"Puissance 4","text":"Puissance 4 demande d’aligner quatre jetons."},
  {"id":"arcade-tic-tac-toe","title":"Morpion","text":"Morpion demande d’aligner trois symboles."},
  {"id":"arcade-board","title":"Partie et état","text":"La zone montre votre partie. Impossible de changer de jeu quand une partie est enclenchée."},
  {"id":"arcade-rules","title":"Règles et gains","text":"Consultez les règles et les gains de chaque jeu depuis ce panneau."},
  {"id":"arcade-scores","title":"Score et XP quotidienne","text":"Ce bandeau distingue votre score du jeu, votre total Arcade et l’état de l’XP du jour."},
  {"id":"arcade-records","title":"Records Arcade","text":"Records permet de consulter performances personnelles et classements par jeu et difficulté."},
  {"id":"contest-legends","title":"Thème et Légendes","text":"Lorsqu’un personnage est C6, il obtient des stats et peut participer aux concours."},
  {"id":"contest-lobby","title":"Participation et préparation","text":"L’entrée et le lobby permettent de choisir une Légende pour participer."},
  {"id":"contest-play","title":"Déroulement et spectateurs","text":"Dans un lobby, des participants et des spectateurs peuvent rejoindre pour assister au concours."},
  {"id":"contest-history","title":"Historique des Concours","text":"Consultez les résultats des Concours terminés depuis l’historique."},
  {"id":"inventory-all","title":"Tout le Sac","text":"L’onglet « Tout » rassemble l’ensemble de vos ressources du Sac."},
  {"id":"inventory-resources","title":"Ressources et raccourcis","text":"Liste des ressources et raccourcis disponibles via un clic sur certaines ressources."},
  {"id":"inventory-objects","title":"Objets","text":"Les objets indiquent leurs usages et leurs détails d’obtention."},
  {"id":"inventory-detail","title":"Détails d’un objet","text":"Consultez les informations d’un objet depuis sa carte."},
  {"id":"inventory-collection","title":"Collection","text":"Collection présente les objets de collection provenant des événements."},
  {"id":"inventory-conversion","title":"Conversion des particules","text":"Convertissez normalement vos particules personnelles depuis ce panneau ou allez échanger avec d’autres joueurs."},
  {"id":"bank-balances","title":"Portefeuille, Banque, Patrimoine","text":"Ces montants distinguent Moras disponibles, Moras déposés et patrimoine total."},
  {"id":"bank-interest","title":"Intérêts","text":"Le taux, la prochaine échéance et l’estimation sont calculés selon votre situation financière."},
  {"id":"bank-transfer","title":"Déposer et retirer","text":"Déposer et Retirer transfèrent réellement vos Moras. MAX propose la quantité maximale disponible."},
  {"id":"bank-history","title":"Opérations bancaires","text":"Les opérations et l’accès à l’historique permettent de retrouver vos mouvements financiers."},
  {"id":"shop-catalog","title":"Catalogue de la Boutique","text":"Le catalogue affiche les offres et leur disponibilité. Prix, quantité, MAX et résultat annoncé se consultent avant un achat."},
  {"id":"shop-tickets","title":"Tickets et probabilités","text":"Les tickets affichent leurs possibilités et probabilités lorsqu’ils sont proposés."},
  {"id":"shop-wallet","title":"Portefeuille et transactions","text":"Retrouvez votre portefeuille, la dernière transaction et l’accès à l’historique."},
  {"id":"codes-available","title":"Codes disponibles","text":"Les codes publiés indiquent période, récompenses et état de récupération. Vous pouvez directement réclamer un code sans le saisir."},
  {"id":"codes-claimed","title":"Codes récupérés","text":"Cette vue conserve les codes déjà récupérés."},
  {"id":"social-friends","title":"Amis et cœurs","text":"Dans l’écran Social, retrouvez vos niveaux d’amitié et cœurs individuels ou groupés."},
  {"id":"social-requests","title":"Demandes reçues et envoyées","text":"Cette vue permet de visionner, accepter ou annuler des demandes envoyées et reçues."},
  {"id":"social-players","title":"Annuaire des joueurs","text":"Recherche, filtres et pagination permettent de trouver un joueur."},
  {"id":"social-profiles","title":"Profil et relation","text":"Consultez la liste des joueurs. L’accès aux Profils des joueurs et les informations disponibles dépendent de la relation et des paramètres de confidentialité de chacun."},
  {"id":"trades-stocks","title":"Total, réservé, disponible","text":"Écran d’échange de particules. Les stocks distinguent toutes vos particules, celles engagées dans des demandes et celles encore disponibles."},
  {"id":"trades-partners","title":"Proposer un échange","text":"Recherchez un partenaire réel puis indiquez la quantité, avec MAX si nécessaire."},
  {"id":"trades-received","title":"Demandes reçues","text":"Acceptation et refus concernent les demandes réellement reçues."},
  {"id":"trades-sent","title":"Demandes envoyées","text":"Retrouvez vos propositions et leur annulation possible."},
  {"id":"trades-history","title":"Échanges effectifs","text":"L’historique conserve les échanges effectivement réalisés."},
  {"id":"profile-overview","title":"Votre Profil","text":"Votre profil. L’onglet « Aperçu » rassemble votre identité et vos informations personnelles. Les profils d’autrui restent soumis aux permissions."},
  {"id":"profile-team","title":"Équipe dans le Profil","text":"Team active présente votre formation dans le Profil. Sa visibilité pour les autres joueurs suit votre confidentialité."},
  {"id":"profile-box","title":"Possessions dans le Profil","text":"La Box du Profil présente vos possessions autorisées. Elle se distingue de la gestion complète dans Personnages."},
  {"id":"profile-collection","title":"Collection dans le Profil","text":"Cette rubrique présente votre Collection selon les droits de consultation. Une rubrique privée conserve son état privé."},
  {"id":"profile-statistics","title":"Statistiques","text":"Vos statistiques regroupent les activités enregistrées. L’accès aux classements respecte la confidentialité des catégories."},
  {"id":"profile-missions","title":"Missions dans le Profil","text":"Cette rubrique présente votre progression permanente autorisée. Les conditions secrètes des Missions verrouillées ne sont pas révélées."},
  {"id":"profile-avatars","title":"Avatars","text":"La Personnalisation distingue avatars possédés et verrouillés, avec l’aperçu équipé et l’avatar élémentaire."},
  {"id":"profile-titles","title":"Titres","text":"Choisissez un titre possédé ou l’absence de titre."},
  {"id":"rankings-categories","title":"Catégories et métriques","text":"Consultation des classements entre joueurs. Choisissez une catégorie puis une métrique."},
  {"id":"rankings-list","title":"Liste et rang personnel","text":"Parcourez la liste et ses pages pour retrouver votre rang. Une donnée privée ou une absence de rang reste indiquée sans changer vos préférences."},
  {"id":"history-invocations","title":"Historique des Invocations","text":"Retrouvez les Invocations réellement enregistrées et parcourez leurs pages."},
  {"id":"history-banners","title":"Historique des bannières","text":"Les snapshots disponibles retracent les rotations."},
  {"id":"history-bank","title":"Historique bancaire","text":"Consultez les mouvements bancaires et leurs filtres."},
  {"id":"history-shop","title":"Historique Boutique","text":"Cette catégorie rassemble vos transactions Boutique disponibles."},
  {"id":"history-event","title":"Historique Event","text":"Consultez les éditions enregistrées."},
  {"id":"chat-thread","title":"Chat global","text":"Chat global en temps réel entre les joueurs. Le fil présente messages, réponses, mentions et actions disponibles."},
  {"id":"chat-composer","title":"Écrire dans le Chat","text":"Saisissez normalement un message ou une commande dans cette zone."},
  {"id":"community-players","title":"Joueurs connectés","text":"Cette liste présente les joueurs connectés et les accès sociaux. Les choix de confidentialité restent respectés."},
  {"id":"dm-conversations","title":"Conversations privées","text":"Les MP regroupent vos conversations privées entre joueurs et leurs non-lus."},
  {"id":"dm-archives","title":"Archives","text":"Archives rassemble les conversations déjà archivées."},
  {"id":"dm-new","title":"Nouveau message privé","text":"Cette entrée permet de chercher un destinataire autorisé et d’envoyer un nouveau message privé."},
  {"id":"dm-thread","title":"Fil privé et confidentialité","text":"Le fil et ses actions suivent la relation réelle, les blocages et la confidentialité."},
  {"id":"dm-history","title":"Historique complet des MP","text":"L’historique complet permet de retrouver les messages disponibles avec ses filtres."},
  {"id":"configuration-menu","title":"Organisation du Menu","text":"Ordre des boutons du Menu. Personnalisez-le comme vous le souhaitez."},
  {"id":"configuration-privacy","title":"Confidentialité","text":"Les catégories utilisent les niveaux Public, Amis ou Privé."},
  {"id":"configuration-account","title":"Compte","text":"Cette rubrique présente les fonctions de compte accessibles au joueur et leur disponibilité."},
  {"id":"conclusion","title":"À vous de jouer","text":"Vous pouvez reprendre ou rejouer le Tutoriel depuis Menu. « Terminer » ou le dernier clic sur « Suivant » clôt ce parcours. Amusez-vous bien !"},
]

it('keeps all 116 surviving IDs, titles and descriptions in the exact owner-approved order', () => {
  expect(tutorialSteps.map(({ id, title, text }) => ({ id, title, text }))).toEqual(ownerCopy)
})
