/** Presentation phrases adapted from the twelve original themes. No rules, RNG or runtime JSON. */
export const eventChatThemes = {
  "new-year": {
    gameAOutside: "⚠️ {username}, ce n’est pas le bon moment pour lancer un feu d’artifice. Fenêtres du jour : {window1} | {window2} | {window3}",
    gameAFail: "🎇 {username} tente d’allumer un feu d’artifice... mais la mèche s’éteint. Retente avant la fin de la fenêtre de temps !",
    gameASuccess: "✅ 🎆 {username} lance un magnifique feu d’artifice du Nouvel An !",
    gameAAlready: "{username}, tu as déjà lancé ton feu d’artifice du jour. Reviens demain !",
    gameBFail: "🎆 {username} tente d’ouvrir le coffre avec le code {code}... le coffre reste fermé. Essais restants : {triesLeft}/{maximum}",
    gameBFound: "✅ 🎁 {username} ouvre le coffre de fortune avec le code {code} !",
    gameBAlreadyFound: "⚠️ Le coffre de fortune du jour a déjà été ouvert avec le code {winningCode}. Reviens demain !",
    gameCSelf: "{username}, tu ne peux pas t’envoyer un vœu à toi-même.",
    gameCAlready: "{username}, tu as déjà envoyé ton vœu du jour. Reviens demain !",
    gameCSuccess: "✅ 🎊 {username} envoie un vœu du Nouvel An à {target} !",
  },
  "hearts": {
    gameAOutside: "⚠️ {username}, ce n’est pas le bon moment pour invoquer un cœur étincelant. Fenêtres du jour : {window1} | {window2} | {window3}",
    gameAFail: "💕 {username} tente d'invoquer un cœur étincelant... mais la magie ne prend pas. Retente avant la fin de la fenêtre de temps !",
    gameASuccess: "✅ 💖 {username} fait apparaître un magnifique cœur étincelant !",
    gameAAlready: "{username}, tu as déjà invoqué ton cœur étincelant du jour. Reviens demain !",
    gameBFail: "🎁 {username} tente d’ouvrir le cadeau avec le code {code}... il reste fermé. Essais restants : {triesLeft}/{maximum}",
    gameBFound: "✅ 🎀 {username} ouvre le cadeau mystère avec le code {code} !",
    gameBAlreadyFound: "⚠️ Le cadeau mystère du jour a déjà été ouvert avec le code {winningCode}. Reviens demain !",
    gameCSelf: "{username}, tu ne peux pas t’envoyer un mot doux à toi-même.",
    gameCAlready: "{username}, tu as déjà envoyé ton mot doux du jour. Reviens demain !",
    gameCSuccess: "✅ 💌 {username} envoie un mot doux à {target} !",
  },
  "spring": {
    gameAOutside: "⚠️ {username}, ce n’est pas le bon moment pour faire pousser un bourgeon. Fenêtres du jour : {window1} | {window2} | {window3}",
    gameAFail: "🌿 {username} arrose son bourgeon... mais rien ne pousse encore. Retente avant la fin de la fenêtre de temps !",
    gameASuccess: "✅ 🌱 {username} fait éclore un magnifique bourgeon printanier !",
    gameAAlready: "{username}, tu as déjà fait pousser ton bourgeon du jour. Reviens demain !",
    gameBFail: "🌱 {username} cherche la racine mystique aux coordonnées {code}... rien trouvé. Essais restants : {triesLeft}/{maximum}",
    gameBFound: "✅ 🌳 {username} découvre la racine mystique aux coordonnées {code} !",
    gameBAlreadyFound: "⚠️ La racine mystique du jour a déjà été trouvée aux coordonnées {winningCode}. Reviens demain !",
    gameCSelf: "{username}, tu ne peux pas t’envoyer une graine à toi-même.",
    gameCAlready: "{username}, tu as déjà envoyé ta graine du jour. Reviens demain !",
    gameCSuccess: "✅ 🌼 {username} plante une graine d'encouragement pour {target} !",
  },
  "bells": {
    gameAOutside: "⚠️ {username}, ce n’est pas le bon moment pour chercher un œuf. Fenêtres du jour : {window1} | {window2} | {window3}",
    gameAFail: "🥚 {username} fouille les buissons... mais aucun œuf en vue. Retente avant la fin de la fenêtre de temps !",
    gameASuccess: "✅ 🥚 {username} trouve un œuf enchanté !",
    gameAAlready: "{username}, tu as déjà trouvé ton œuf du jour. Reviens demain !",
    gameBFail: "🥚 {username} cherche le panier aux coordonnées {code}... rien trouvé. Essais restants : {triesLeft}/{maximum}",
    gameBFound: "✅ 🧺 {username} trouve le panier de Pâques aux coordonnées {code} !",
    gameBAlreadyFound: "⚠️ Le panier de Pâques du jour a déjà été trouvé aux coordonnées {winningCode}. Reviens demain !",
    gameCSelf: "{username}, tu ne peux pas t’envoyer un chocolat à toi-même.",
    gameCAlready: "{username}, tu as déjà envoyé ton chocolat du jour. Reviens demain !",
    gameCSuccess: "✅ 🍫 {username} offre un chocolat à {target} !",
  },
  "flowers": {
    gameAOutside: "⚠️ {username}, ce n’est pas le bon moment pour cueillir une fleur. Fenêtres du jour : {window1} | {window2} | {window3}",
    gameAFail: "🌷 {username} cherche une fleur rare... mais ne trouve rien. Retente avant la fin de la fenêtre de temps !",
    gameASuccess: "✅ 🌸 {username} cueille une magnifique fleur de printemps !",
    gameAAlready: "{username}, tu as déjà cueilli ta fleur du jour. Reviens demain !",
    gameBFail: "🌸 {username} cherche le bouquet aux coordonnées {code}... rien trouvé. Essais restants : {triesLeft}/{maximum}",
    gameBFound: "✅ 💐 {username} découvre le bouquet légendaire aux coordonnées {code} !",
    gameBAlreadyFound: "⚠️ Le bouquet légendaire du jour a déjà été trouvé aux coordonnées {winningCode}. Reviens demain !",
    gameCSelf: "{username}, tu ne peux pas t’envoyer un mot de printemps à toi-même.",
    gameCAlready: "{username}, tu as déjà envoyé ton mot de printemps du jour. Reviens demain !",
    gameCSuccess: "✅ 🌼 {username} envoie un mot de printemps à {target} !",
  },
  "summer": {
    gameAOutside: "⚠️ {username}, ce n’est pas le bon moment pour pêcher. Fenêtres du jour : {window1} | {window2} | {window3}",
    gameAFail: "🌊 {username} lance sa ligne... rien ne mord. Retente avant la fin de la fenêtre de temps !",
    gameASuccess: "✅ 🎣 {username} pêche un poisson d’été !",
    gameAAlready: "{username}, tu as déjà pêché ton poisson du jour. Reviens demain !",
    gameBFail: "🌊 {username} fouille le sable avec les coordonnées {code}... rien trouvé. Essais restants : {triesLeft}/{maximum}",
    gameBFound: "✅ 🗺️ {username} trouve le trésor d’été aux coordonnées {code} !",
    gameBAlreadyFound: "⚠️ Le trésor du jour a déjà été trouvé aux coordonnées {winningCode}. Reviens demain pour une nouvelle chasse !",
    gameCSelf: "{username}, tu ne peux pas t’envoyer une carte postale à toi-même.",
    gameCAlready: "{username}, tu as déjà envoyé ta carte postale du jour. Reviens demain !",
    gameCSuccess: "✅ 💌 {username} envoie une carte postale d’été à {target} !",
  },
  "stars": {
    gameAOutside: "⚠️ {username}, ce n’est pas le bon moment pour observer une étoile filante. Fenêtres du jour : {window1} | {window2} | {window3}",
    gameAFail: "🌠 {username} scrute le ciel nocturne... mais aucune étoile filante n’apparaît. Retente avant la fin de la fenêtre de temps !",
    gameASuccess: "✅ ⭐ {username} aperçoit une magnifique étoile filante !",
    gameAAlready: "{username}, tu as déjà observé ton étoile filante du jour. Reviens demain !",
    gameBFail: "⭐ {username} recherche la constellation aux coordonnées {code}... rien trouvé. Essais restants : {triesLeft}/{maximum}",
    gameBFound: "✅ 🌌 {username} découvre la constellation secrète aux coordonnées {code} !",
    gameBAlreadyFound: "⚠️ La constellation secrète du jour a déjà été trouvée aux coordonnées {winningCode}. Reviens demain !",
    gameCSelf: "{username}, tu ne peux pas t’envoyer un vœu à toi-même.",
    gameCAlready: "{username}, tu as déjà envoyé ton vœu du jour. Reviens demain !",
    gameCSuccess: "✅ 💫 {username} adresse un vœu sous les étoiles à {target} !",
  },
  "adventurers": {
    gameAOutside: "⚠️ {username}, ce n’est pas le bon moment pour partir en expédition. Fenêtres du jour : {window1} | {window2} | {window3}",
    gameAFail: "🗺️ {username} explore les environs... mais ne découvre rien d’intéressant. Retente avant la fin de la fenêtre de temps !",
    gameASuccess: "✅ 🧭 {username} revient d’expédition avec une relique rare !",
    gameAAlready: "{username}, tu as déjà terminé ton expédition du jour. Reviens demain !",
    gameBFail: "🧭 {username} explore la ruine aux coordonnées {code}... rien trouvé. Essais restants : {triesLeft}/{maximum}",
    gameBFound: "✅ 🏛️ {username} découvre la ruine antique aux coordonnées {code} !",
    gameBAlreadyFound: "⚠️ La ruine antique du jour a déjà été trouvée aux coordonnées {winningCode}. Reviens demain !",
    gameCSelf: "{username}, tu ne peux pas t’envoyer une note de voyage à toi-même.",
    gameCAlready: "{username}, tu as déjà envoyé ta note de voyage du jour. Reviens demain !",
    gameCSuccess: "✅ 📖 {username} partage une note de voyage avec {target} !",
  },
  "harvest": {
    gameAOutside: "⚠️ {username}, ce n’est pas le bon moment pour récolter. Fenêtres du jour : {window1} | {window2} | {window3}",
    gameAFail: "🌾 {username} inspecte les champs... mais rien n’est prêt à être récolté. Retente avant la fin de la fenêtre de temps !",
    gameASuccess: "✅ 🌾 {username} réalise une belle récolte !",
    gameAAlready: "{username}, tu as déjà effectué ta récolte du jour. Reviens demain !",
    gameBFail: "🌾 {username} fouille le grenier aux coordonnées {code}... rien trouvé. Essais restants : {triesLeft}/{maximum}",
    gameBFound: "✅ 🏚️ {username} découvre le grenier ancien aux coordonnées {code} !",
    gameBAlreadyFound: "⚠️ Le grenier ancien du jour a déjà été trouvé aux coordonnées {winningCode}. Reviens demain !",
    gameCSelf: "{username}, tu ne peux pas t’envoyer un panier à toi-même.",
    gameCAlready: "{username}, tu as déjà partagé ton panier du jour. Reviens demain !",
    gameCSuccess: "✅ 🧺 {username} partage un panier de récolte avec {target} !",
  },
  "shadows": {
    gameAOutside: "⚠️ {username}, ce n’est pas le bon moment pour traquer un fantôme. Fenêtres du jour : {window1} | {window2} | {window3}",
    gameAFail: "👻 {username} explore les ténèbres... mais aucun fantôme n’apparaît. Retente avant la fin de la fenêtre de temps !",
    gameASuccess: "✅ 👻 {username} capture un fantôme farceur !",
    gameAAlready: "{username}, tu as déjà capturé ton fantôme du jour. Reviens demain !",
    gameBFail: "🎃 {username} explore la crypte aux coordonnées {code}... rien trouvé. Essais restants : {triesLeft}/{maximum}",
    gameBFound: "✅ 🪦 {username} découvre la crypte hantée aux coordonnées {code} !",
    gameBAlreadyFound: "⚠️ La crypte hantée du jour a déjà été trouvée aux coordonnées {winningCode}. Reviens demain !",
    gameCSelf: "{username}, tu ne peux pas te lancer un sort à toi-même.",
    gameCAlready: "{username}, tu as déjà lancé ton sort du jour. Reviens demain !",
    gameCSuccess: "✅ 🧙 {username} lance un sort à {target} !",
  },
  "mists": {
    gameAOutside: "⚠️ {username}, ce n’est pas le bon moment pour suivre une feuille portée par le vent. Fenêtres du jour : {window1} | {window2} | {window3}",
    gameAFail: "🍂 {username} suit une feuille dans la brume... mais elle disparaît dans le brouillard. Retente avant la fin de la fenêtre de temps !",
    gameASuccess: "✅ 🍁 {username} retrouve une feuille ancienne portée par le vent !",
    gameAAlready: "{username}, tu as déjà retrouvé ta feuille ancienne du jour. Reviens demain !",
    gameBFail: "🍁 {username} recherche la relique aux coordonnées {code}... rien trouvé. Essais restants : {triesLeft}/{maximum}",
    gameBFound: "✅ 🏺 {username} découvre la relique oubliée aux coordonnées {code} !",
    gameBAlreadyFound: "⚠️ La relique oubliée du jour a déjà été trouvée aux coordonnées {winningCode}. Reviens demain !",
    gameCSelf: "{username}, tu ne peux pas t’envoyer un murmure à toi-même.",
    gameCAlready: "{username}, tu as déjà envoyé ton murmure du jour. Reviens demain !",
    gameCSuccess: "✅ 🌫️ {username} adresse un murmure à {target} !",
  },
  "christmas": {
    gameAOutside: "⚠️ {username}, ce n’est pas le bon moment pour préparer un cadeau de Noël. Fenêtres du jour : {window1} | {window2} | {window3}",
    gameAFail: "🎁 {username} emballe un cadeau... mais il manque encore quelque chose. Retente avant la fin de la fenêtre de temps !",
    gameASuccess: "✅ 🎁 {username} prépare un magnifique cadeau de Noël !",
    gameAAlready: "{username}, tu as déjà préparé ton cadeau de Noël du jour. Reviens demain !",
    gameBFail: "🎄 {username} fouille la hotte du Père Noël aux coordonnées {code}... rien trouvé. Essais restants : {triesLeft}/{maximum}",
    gameBFound: "✅ 🎅 {username} découvre la hotte du Père Noël aux coordonnées {code} !",
    gameBAlreadyFound: "⚠️ La hotte du Père Noël du jour a déjà été trouvée aux coordonnées {winningCode}. Reviens demain !",
    gameCSelf: "{username}, tu ne peux pas t’envoyer une carte à toi-même.",
    gameCAlready: "{username}, tu as déjà envoyé ta carte du jour. Reviens demain !",
    gameCSuccess: "✅ 💌 {username} envoie une carte de Noël à {target} !",
  },
} as const;
