import { randomUUID } from 'node:crypto';
import type { PrismaClient } from '../generated/prisma/client.js';
import { bootstrapPlayer } from '../src/infrastructure/database/player-bootstrap.js';

let fixtureSequence = 0;

/** Synthetic only: broad real schema plus scalable, payload-heavy personal history. */
export async function canonicalizationFixture(db: PrismaClient, scale = 1) {
  const subject = randomUUID(), twitchUserId = String(980000000000 + ++fixtureSequence), now = new Date('2026-01-02T12:00:00Z');
  const player = await db.$transaction(tx => bootstrapPlayer(tx, { displayName: 'Synthetic R1055', webIdentity: { provider: 'fixture', providerSubject: subject } }));
  const playerId = player.id;
  await db.playerProgression.update({ where: { playerId }, data: { xp: 999n, totalMessages: 9007199254740993n } });
  const operations = Array.from({ length: 2000 * scale }, () => randomUUID());
  await db.businessOperation.createMany({ data: operations.map(id => ({ id, playerId, operationType: 'fixture.r1055', sourceChannel: 'UI', status: 'COMPLETED', completedAt: now, resultSummary: { synthetic: 'fixture'.repeat(216) } })) });
  await db.resourceMovement.createMany({ data: operations.slice(0, 1600 * scale).map(operationId => ({ playerId, resourceKey: 'primogems', delta: 1n, balanceBefore: 9007199254740992n, balanceAfter: 9007199254740993n, causeKey: 'fixture', domainKey: 'fixture', operationId, sourceChannel: 'UI' })) });
  const sessions = Array.from({ length: 30 * scale }, () => randomUUID());
  await db.arcadeSession.createMany({ data: sessions.map(id => ({ id, playerId, game: 'MEMORY', difficulty: 'EASY', status: 'ABANDONED', firstSide: 'PLAYER', privateState: {}, randomState: 1n, banterId: 'fixture', nextActionAt: now, finishedAt: now })) });
  await db.arcadeReceipt.createMany({ data: operations.slice(0, 1100 * scale).map((operationId, i) => ({ playerId, sessionId: sessions[i % sessions.length]!, operationId, idempotencyKey: randomUUID(), fingerprint: 'a'.repeat(64), response: { synthetic: 'fixture'.repeat(96) } })) });
  const character = await db.character.create({ data: { externalKey: `fixture-${randomUUID()}`, name: 'Synthetic', rarity: 5, elementKey: 'pyro' } }), characterId = character.id;
  const team = await db.team.create({ data: { playerId, displayPosition: 1, members: { create: { characterId, position: 1 } } } });
  await db.playerCharacter.create({ data: { playerId, characterId, constellation: 6, copies: 7, firstObtainedAt: now } });
  await db.c6CompetitionProgress.create({ data: { playerId, characterId, legacyProvenance: { synthetic: true } } });
  const item = await db.itemDefinition.create({ data: { externalKey: `fixture-${randomUUID()}`, displayName: 'Synthetic', category: 'fixture' } });
  await db.playerItem.create({ data: { playerId, itemId: item.id, quantity: 1n } });
  await db.itemAcquisition.create({ data: { playerId, itemId: item.id, quantity: 1n, sourceKey: 'fixture', operationId: operations[0]! } });
  const cosmetic = await db.cosmeticDefinition.create({ data: { externalKey: `fixture-${randomUUID()}`, type: 'TITLE', displayName: 'Synthetic' } });
  await db.playerCosmetic.create({ data: { playerId, cosmeticId: cosmetic.id, unlockSource: 'fixture' } });
  await db.playerBankAccount.create({ data: { playerId, lastInterestDate: now } });
  await db.bankTransaction.create({ data: { playerId, transactionType: 'DEPOSIT', walletBalanceBefore: 1n, walletBalanceAfter: 0n, amount: 1n, bankBalanceBefore: 0n, bankBalanceAfter: 1n, operationId: operations[1]! } });
  await db.playerWheelDailyState.create({ data: { playerId, businessDate: now, spunAt: now, resultKnown: false, legacyProvenance: { synthetic: true } } });
  await db.playerExpedition.create({ data: { playerId } });
  await db.playerCombatStats.create({ data: { playerId } });
  await db.playerCharacterCombatStats.create({ data: { playerId, characterId } });
  await db.playerDailyCombatLoadout.create({ data: { playerId } });
  await db.playerDailyCombatLoadoutSlot.create({ data: { playerId, characterId, position: 1 } });
  await db.playerBossLoadout.create({ data: { playerId } });
  await db.playerBossLoadoutSlot.create({ data: { playerId, characterId, position: 1 } });
  await db.playerBossStats.create({ data: { playerId } });
  await db.playerFavorState.create({ data: { playerId } });
  await db.favorGrant.create({ data: { playerId, requestedDays: 1, addedDays: 1, blockedDays: 0, immediatePrimogems: 0n, compensationPrimogems: 0n, operationId: operations[2]! } });
  await db.favorDailyClaim.create({ data: { playerId, businessDate: now, claimedAt: now, sourceChannel: 'UI', operationId: operations[3]! } });
  await db.playerSocialStats.create({ data: { playerId } });
  await db.playerActivityState.create({ data: { playerId } });
  await db.playerPreference.create({ data: { playerId, preferenceKey: 'fixture', value: true } });
  await db.notification.createMany({ data: Array.from({ length: 76 * scale + 1 }, () => ({ playerId, domainKey: 'fixture', typeKey: 'fixture', payload: {} })) });
  await db.arcadeStat.create({ data: { playerId, game: 'MEMORY', difficulty: 'EASY', played: 1, losses: 1, bestPairs: 0, bestPoints: 1, bestOutcome: 'LOSS', bestSessionId: sessions[0]! } });
  await db.arcadeDailyGrant.create({ data: { playerId, game: 'MEMORY', businessDate: now, sessionId: sessions[0]!, operationId: operations[4]!, xpAwarded: 1 } });
  const encounter = await db.dailyCombatEncounter.upsert({ where: { businessDate: now }, create: { businessDate: now }, update: {} });
  await db.playerDailyCombatState.create({ data: { playerId, encounterId: encounter.id } });
  await db.playerDailyCombatKo.create({ data: { playerId, encounterId: encounter.id, characterId } });
  const attempt = await db.dailyCombatAttempt.create({ data: { playerId, encounterId: encounter.id, mode: 'MANUAL', chanceHalfPoints: 10, won: false, rngRoll: 99, operationId: operations[5]! } });
  await db.dailyCombatAttemptMember.create({ data: { attemptId: attempt.id, position: 1, characterId, raritySnapshot: 5, constellationSnapshot: 6, elementKeySnapshot: 'pyro', contributionHalfPoints: 10 } });
  await db.contestDailyTheme.upsert({ where: { businessDate: now }, create: { businessDate: now, theme: 'INTELLIGENCE' }, update: {} });
  const contest = await db.contest.create({ data: { businessDate: now, theme: 'INTELLIGENCE', status: 'CANCELLED', phase: 'CANCELLED', cancellationKind: 'TECHNICAL', cancelledAt: now } });
  await db.contestDailyParticipation.create({ data: { playerId, businessDate: now, contestId: contest.id, consumedAt: now } });
  await db.contestReward.create({ data: { playerId, contestId: contest.id, rank: 1, primogems: 1n, operationId: operations[6]!, awardedAt: now } });
  const batch = await db.migrationBatch.create({ data: { snapshotHash: 'b'.repeat(64), mode: 'REHEARSAL', migratorVersion: 'fixture' } });
  await db.contestLegacyDailyLock.create({ data: { playerId, businessDate: new Date('2026-01-01'), batchId: batch.id, legacyProvenance: { synthetic: true } } });
  const giveaway = await db.giveawaySession.create({ data: { status: 'CLOSED', legacyProvenance: { synthetic: true } } });
  await db.giveawayChatStat.create({ data: { playerId, sessionId: giveaway.id, messageCount: 1n } });
  await db.giveawayWin.create({ data: { playerId, sessionId: giveaway.id, drawIndex: 1, origin: 'LEGACY', legacyProvenance: { synthetic: true } } });
  await db.giveawayReward.create({ data: { playerId, sessionId: giveaway.id, kind: 'DRAW', amount: 1600n, operationId: operations[7]! } });
  const boss = await db.monthlyBoss.create({ data: { monthStart: new Date(Date.UTC(1800, ++fixtureSequence, 1)), nameSnapshot: 'Synthetic', baseHp: 500000n, hpVariationPercent: 0, maxHp: 500000n, currentHp: 0n, finalBlowPlayerId: playerId, defeatedAt: now, resistanceElementKey: 'pyro' } });
  await db.playerBossParticipation.create({ data: { playerId, bossId: boss.id, totalDamage: 1n, attackCount: 1n, bestHit: 1n, firstAttackAt: now, lastAttackAt: now } });
  const attack = await db.bossAttack.create({ data: { playerId, bossId: boss.id, businessDate: now, damage: 1n, operationId: operations[8]! } });
  await db.bossAttackMember.create({ data: { attackId: attack.id, position: 1, characterId, characterNameSnapshot: 'Synthetic', raritySnapshot: 5, elementKeySnapshot: 'pyro', constellationSnapshot: 6, damageBeforeResistance: 1n, resistanceApplied: false, damage: 1n } });
  await db.bossLegacyContribution.create({ data: { playerId, bossId: boss.id, batchId: batch.id, legacyProvenance: { synthetic: true } } });
  const identity = await db.webIdentity.findUniqueOrThrow({ where: { playerId } });
  return { playerId, identity, subject, twitchUserId, operations, teamId: team.id };
}
