import { useState } from 'react'
import type { DailyRewardClaimDto, DailyRewardTodayDto, ElementKey, WheelSpinDto, WheelTodayDto } from '../api/types'
import WheelCard from '../components/WheelCard'
import DailyRewardCard from '../components/DailyRewardCard'
import ScreenHeader from '../components/ScreenHeader'
import type { ScreenId } from '../types'

function ActivitiesScreen({ screen, wheelToday, onSpinWheel, dailyRewardToday, elementKey, onClaimDailyReward }: { screen: ScreenId; wheelToday: WheelTodayDto; onSpinWheel: () => Promise<WheelSpinDto>; dailyRewardToday: DailyRewardTodayDto; elementKey: ElementKey; onClaimDailyReward: () => Promise<DailyRewardClaimDto> }) {
  if (screen === 'activities-dailies') return <DailiesScreen wheelToday={wheelToday} onSpinWheel={onSpinWheel} dailyRewardToday={dailyRewardToday} elementKey={elementKey} onClaimDailyReward={onClaimDailyReward} />
  const content = screen === 'activities-missions' ? { title: 'Missions', description: 'Les missions permanentes seront disponibles ici.', tabs: ['B', 'A', 'S', 'Z'] } : screen === 'activities-combat' ? { title: 'Combat', description: 'Le domaine Combat n’est pas encore disponible dans cette version.', tabs: ['Entraînement', 'Boss'] } : screen === 'activities-event' ? { title: 'Événement', description: 'Les événements mensuels seront accessibles ici.', tabs: ['Jeux', 'Shop', 'Classement'] } : { title: 'Concours', description: 'Le Concours C6 sera accessible ici lorsqu’il sera implémenté.', tabs: [] }
  return <div className="screen-content activity-shell"><ScreenHeader eyebrow="Activités" title={content.title} description={content.description} /><nav className="activity-inner-tabs" aria-label={`Sections ${content.title}`}>{content.tabs.map((tab) => <button type="button" disabled key={tab}>{tab}</button>)}</nav><section className="panel unavailable-shell"><strong>Bientôt disponible</strong><p>Aucune progression fictive n’est affichée.</p></section></div>
}

function DailiesScreen({ wheelToday, onSpinWheel, dailyRewardToday, elementKey, onClaimDailyReward }: { wheelToday: WheelTodayDto; onSpinWheel: () => Promise<WheelSpinDto>; dailyRewardToday: DailyRewardTodayDto; elementKey: ElementKey; onClaimDailyReward: () => Promise<DailyRewardClaimDto> }) {
  const [tab, setTab] = useState<'overview' | 'wheel' | 'challenge'>('overview')
  return <div className="screen-content activity-shell"><ScreenHeader eyebrow="Activités" title="Quotidiennes" description="Retrouvez ici les activités réellement disponibles aujourd’hui." /><nav className="activity-inner-tabs" aria-label="Sections Quotidiennes"><button className={tab === 'overview' ? 'active' : ''} onClick={() => setTab('overview')}>Aperçu</button><button className={tab === 'wheel' ? 'active' : ''} onClick={() => setTab('wheel')}>Roue</button><button className={tab === 'challenge' ? 'active' : ''} onClick={() => setTab('challenge')}>Défi</button></nav>{tab === 'overview' && <div className="dailies-overview"><DailyRewardCard today={dailyRewardToday} elementKey={elementKey} onClaim={onClaimDailyReward} /><button type="button" className="panel daily-summary-link" onClick={() => setTab('wheel')}><strong>Roue astrale</strong><span>{wheelToday.spun ? 'Fait aujourd’hui' : 'À faire'}</span></button><section className="panel unavailable-shell"><strong>Défi</strong><p>Indisponible tant que son service métier n’est pas implémenté.</p></section></div>}{tab === 'wheel' && <WheelCard today={wheelToday} onSpin={onSpinWheel} />}{tab === 'challenge' && <section className="panel unavailable-shell"><strong>Défi indisponible</strong><p>Cette activité n’est pas encore implémentée. Aucune progression n’est simulée.</p></section>}</div>
}
export default ActivitiesScreen
