import { useCallback, useEffect, useState, type FormEvent } from 'react'
import type { ModerationPlayerDto, ModerationStateDto } from '../api/types'
import type { ModerationGachaInput, ModerationResourceInput, ModerationXpInput } from '../moderation/moderation-intent-coordinator'
import { apiErrorMessage } from '../utils/formatters'
type Props = { actorPlayerId: string; capabilities: ModerationStateDto['permissions']['capabilities']; onLoad: (targetPlayerId?: string) => Promise<ModerationStateDto>; onSearchPlayers: (query: string) => Promise<readonly ModerationPlayerDto[]>; onResource: (targetPlayerId: string, input: ModerationResourceInput) => Promise<ModerationStateDto>; onXp: (targetPlayerId: string, input: ModerationXpInput) => Promise<ModerationStateDto>; onGacha: (targetPlayerId: string, input: ModerationGachaInput) => Promise<ModerationStateDto>; onStella: (targetPlayerId: string, quantity: string) => Promise<ModerationStateDto>; onTester: (targetPlayerId: string, enabled: boolean, idempotencyKey: string) => Promise<ModerationStateDto>; onApplied: (state: ModerationStateDto) => void }
const resources = [['primogems', 'Primos'], ['moras', 'Moras'], ['particles_pyro', 'Pyro'], ['particles_hydro', 'Hydro'], ['particles_cryo', 'Cryo'], ['particles_electro', 'Electro'], ['particles_anemo', 'Anémo'], ['particles_geo', 'Géo'], ['particles_dendro', 'Dendro']] as const
const integerText = (value: string) => value.replace(/[^0-9]/g, '')
function ModerationScreen({ actorPlayerId, capabilities, onLoad, onSearchPlayers, onResource, onXp, onGacha, onStella, onTester, onApplied }: Props) {
  const [state, setState] = useState<ModerationStateDto | null>(null); const [query, setQuery] = useState(''); const [players, setPlayers] = useState<readonly ModerationPlayerDto[]>([]); const [resourceKey, setResourceKey] = useState('primogems'); const [amount, setAmount] = useState('160'); const [xp, setXp] = useState(''); const [pity5, setPity5] = useState(''); const [pity4, setPity4] = useState(''); const [capture, setCapture] = useState(''); const [guarantee, setGuarantee] = useState(false); const [stella, setStella] = useState('0'); const [pending, setPending] = useState(false); const [message, setMessage] = useState<string | null>(null)
  const targetId = state?.player.id ?? actorPlayerId; const isSuper = capabilities.superTools; const isSelf = targetId === actorPlayerId
  const hydrate = (value: ModerationStateDto) => { setXp(value.progression.totalXp); setPity5(String(value.gachaState.pity5)); setPity4(String(value.gachaState.pity4)); setCapture(String(value.gachaState.captureProgress)); setGuarantee(value.gachaState.guaranteedFeatured5); setStella(value.stella.quantity) }
  const accept = useCallback((value: ModerationStateDto) => { setState(value); hydrate(value); onApplied(value); setMessage(null) }, [onApplied])
  useEffect(() => { let active = true; void onLoad().then((value) => { if (active) accept(value) }).catch((error) => { if (active) setMessage(apiErrorMessage(error)) }); return () => { active = false } }, [accept, onLoad])
  useEffect(() => { if (!isSuper) return; let active = true; const timer = window.setTimeout(() => void onSearchPlayers(query).then((value) => { if (active) setPlayers(value) }).catch((error) => { if (active) setMessage(apiErrorMessage(error)) }), 120); return () => { active = false; window.clearTimeout(timer) } }, [isSuper, onSearchPlayers, query])
  const execute = async (action: () => Promise<ModerationStateDto>) => { if (pending) return; setPending(true); setMessage(null); try { accept(await action()) } catch (error) { setMessage(apiErrorMessage(error)) } finally { setPending(false) } }
  const submit = (event: FormEvent, action: () => Promise<ModerationStateDto>) => { event.preventDefault(); void execute(action) }; const selectTarget = (id: string) => void execute(() => onLoad(id))
  return <div className="screen-content moderation-screen"><header className="moderation-title"><span className="eyebrow">Modération</span><h1>Outils de test</h1><p>Rang : {isSuper ? 'Super' : 'Testeur'}</p></header>{message && <p className="moderation-feedback error" role="alert">{message}</p>}{isSuper && <section className="panel moderation-target"><label>Joueur ciblé<input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Rechercher un joueur actif…" /></label><div className="moderation-target-list"><button type="button" className={isSelf ? 'active' : ''} disabled={pending} onClick={() => selectTarget(actorPlayerId)}>Moi</button>{players.map((candidate) => <button type="button" className={candidate.id === targetId ? 'active' : ''} disabled={pending} onClick={() => selectTarget(candidate.id)} key={candidate.id}>{candidate.displayName} · niv. {candidate.level}{candidate.tester ? ' · Testeur' : ''}</button>)}</div>{state && <small>Cible : {state.player.displayName}</small>}</section>}<div className="moderation-grid">
    <form className="panel moderation-tool" onSubmit={(event) => submit(event, () => onResource(targetId, { resourceKey, amount, direction: 'add' }))}><h2>Ressources</h2><label>Ressource<select value={resourceKey} onChange={(event) => setResourceKey(event.target.value)}>{resources.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>Montant<input inputMode="numeric" pattern="[0-9]*" required value={amount} onChange={(event) => setAmount(integerText(event.target.value))} /></label><div className="moderation-actions"><button disabled={pending}>Ajouter</button><button type="button" disabled={pending} onClick={() => void execute(() => onResource(targetId, { resourceKey, amount, direction: 'remove' }))}>Retirer</button></div></form>
    {isSuper && <><form className="panel moderation-tool" onSubmit={(event) => submit(event, () => onXp(targetId, { totalXp: xp }))}><h2>Progression</h2><label>XP totale<input inputMode="numeric" pattern="[0-9]*" required value={xp} onChange={(event) => setXp(integerText(event.target.value))} /></label><div className="moderation-actions"><button disabled={pending}>Définir l’XP</button><button type="button" disabled={pending} onClick={() => void execute(() => onXp(targetId, { prepareNextLevel: true }))}>Préparer prochain niveau</button></div>{state && <small>Niveau {state.progression.level} · {state.progression.xpIntoCurrentStep} / {state.progression.xpPerStep} XP</small>}</form><form className="panel moderation-tool" onSubmit={(event) => submit(event, () => onGacha(targetId, { pity5: Number(pity5), pity4: Number(pity4), captureProgress: Number(capture), guaranteedFeatured5: guarantee }))}><h2>Gacha</h2><div className="moderation-inline"><label>Pity 5★<input inputMode="numeric" pattern="[0-9]*" required value={pity5} onChange={(event) => setPity5(integerText(event.target.value))} /></label><button type="button" onClick={() => setPity5('89')}>89</button><label>Pity 4★<input inputMode="numeric" pattern="[0-9]*" required value={pity4} onChange={(event) => setPity4(integerText(event.target.value))} /></label><button type="button" onClick={() => setPity4('9')}>9</button></div><label>Capture (0–3)<input inputMode="numeric" pattern="[0-9]*" required value={capture} onChange={(event) => setCapture(integerText(event.target.value))} /></label><label className="moderation-check"><input type="checkbox" checked={guarantee} onChange={(event) => setGuarantee(event.target.checked)} />Garantie 5★</label><button disabled={pending}>Appliquer</button></form><form className="panel moderation-tool" onSubmit={(event) => submit(event, () => onStella(targetId, stella))}><h2>Objets</h2><label>Masterless Stella Fortuna<input inputMode="numeric" pattern="[0-9]*" required value={stella} onChange={(event) => setStella(integerText(event.target.value))} /></label><button disabled={pending}>Définir la quantité</button></form>{!isSelf && <section className="panel moderation-tool moderation-role"><h2>Testeur</h2><p>{state?.player.tester ? 'Ce joueur possède actuellement le rôle Testeur.' : 'Ce joueur ne possède pas le rôle Testeur.'}</p><button disabled={pending} type="button" onClick={() => void execute(() => onTester(targetId, !state?.player.tester, crypto.randomUUID()))}>{state?.player.tester ? 'Retirer Testeur' : 'Attribuer Testeur'}</button></section>}</>}
  </div></div>
}
export default ModerationScreen
