import { renderToStaticMarkup } from 'react-dom/server'
import { describe, expect, it, vi } from 'vitest'
import type { CurrentGachaDto, GachaCharacterDto } from '../api/types'
import BannerHero from './BannerHero'

const character = (id: string, rarity: 4 | 5): GachaCharacterDto => ({ id, externalKey: `legacy:${id}`, name: id, rarity, elementKey: 'hydro', weaponType: 'Épée', region: 'Fontaine', classKey: null, iconPath: `/icon/${id}.png`, splashPath: `/splash/${id}.png`, wishPath: `/wish/${id}.png`, fullbodyPath: `/fullbody/${id}.png` })
const five = Array.from({ length: 4 }, (_, index) => character(`Five ${index + 1}`, 5))
const four = Array.from({ length: 6 }, (_, index) => character(`Four ${index + 1}`, 4))
function data(target: string | null): CurrentGachaDto { return { banner: { id: 'banner', startsAt: '2026-09-01T00:00:00Z', endsAt: '2026-09-08T00:00:00Z', featuredFiveStars: five, featuredFourStars: four }, playerState: { pity5: 0, pity4: 0, guaranteedFeatured5: false, captureProgress: 0, fiftyFiftyLostStreak: 0, selectedBannerCharacterId: target, totalPulls: '0', totalFiveStars: '0', totalFourStars: '0', fiftyFiftyWon: '0', fiftyFiftyLost: '0', capturesTriggered: '0' } } }

describe('BannerHero real Gacha state', () => {
  it('offers exactly four showcase targets without featured four-star cards', () => {
    const html = renderToStaticMarkup(<BannerHero gacha={data(null)} onSetTarget={vi.fn()} />)
    expect((html.match(/character-showcase-gacha/g) ?? [])).toHaveLength(4)
    expect((html.match(/large-team-card target-choice/g) ?? [])).toHaveLength(4)
    expect((html.match(/character-portrait-badge/g) ?? [])).toHaveLength(4)
    expect((html.match(/character-portrait-frame/g) ?? [])).toHaveLength(4)
    expect((html.match(/character-portrait-image/g) ?? [])).toHaveLength(4)
    expect((html.match(/large-character-portrait character-display-portrait/g) ?? [])).toHaveLength(4)
    expect((html.match(/class="large-team-copy character-display-copy"/g) ?? [])).toHaveLength(4)
    expect(html).not.toContain('target-choice-portrait')
    expect(html).not.toContain('banner-card-element')
    expect(html).not.toContain('featured-four-stars')
    expect(html).toContain('Choisissez votre cible')
    expect(html).toContain('src="/icon/Five 1.png"')
    expect(html).not.toContain('src="/fullbody/Five 1.png"')
    expect((html.match(/★★★★★/g) ?? [])).toHaveLength(4)
    for (const target of five) expect(html).toContain(`>${target.name}</strong>`)
    for (const featured of four) expect(html).not.toContain(`>${featured.name}</strong>`)
    expect(html).not.toContain('Niveau')
    expect(html).not.toMatch(/>C\d+</)
    expect(html).not.toContain('team-slot-number')
    expect(html).not.toContain('Épée')
    expect(html).not.toContain('Fontaine')
    expect(html).not.toContain('Soutien')
    expect(html).not.toContain('Personnages 4★')
    expect(html).not.toContain('selected-mark')
  })
  it('shows the selected hero hierarchy, real zero state and active pull controls on Invocation', () => {
    const html = renderToStaticMarkup(<BannerHero gacha={data(five[0]!.id)} onSetTarget={vi.fn()} onPull={vi.fn()} onGetHistory={vi.fn()} showDetails />)
    expect(html).toContain('banner-element-watermark')
    expect(html).toContain('src="/splash/Five 1.png"')
    expect(html).not.toContain('src="/icon/Five 1.png"')
    expect(html).toContain('Cible 5★ de la rotation hebdomadaire.</p><p>Pity, Garantie et Capture sont conservées entre les rotations.')
    expect(html).toContain('banner-change-button')
    expect(html).toContain('>Détail<')
    expect(html).not.toContain('banner-meta-stack')
    expect(html).toMatch(/banner-meta-actions[\s\S]*banner-end-date[\s\S]*>Changer<[\s\S]*>Détail<\/button><\/div>/)
    expect(html).not.toContain('banner-detail-row')
    expect(html.indexOf('banner-end-date')).toBeLessThan(html.indexOf('>Changer<'))
    expect(html.indexOf('>Changer<')).toBeLessThan(html.indexOf('>Détail<'))
    expect(html.indexOf('>Détail<')).toBeLessThan(html.indexOf('featured-four-stars'))
    expect(html).toContain('primary-pity')
    expect(html).toContain('gacha-state-secondary')
    expect(html).toContain('Pity 4★')
    expect(html).toContain('Garantie 5★')
    expect(html).toContain('Capture')
    expect((html.match(/character-showcase-featured/g) ?? [])).toHaveLength(6)
    expect((html.match(/featured-element/g) ?? [])).toHaveLength(6)
    expect((html.match(/featured-character-portrait/g) ?? [])).toHaveLength(6)
    expect((html.match(/character-portrait-frame/g) ?? [])).toHaveLength(6)
    expect((html.match(/featured-four-copy/g) ?? [])).toHaveLength(6)
    expect(html).toContain('src="/icon/Four 1.png"')
    expect(html).not.toContain('src="/fullbody/Four 1.png"')
    expect(html).not.toContain('character-card-meta')
    expect(html).not.toContain('Épée')
    expect(html).not.toContain('Fontaine')
    for (const featured of four) expect(html).toContain(`>${featured.name}</strong>`)
    expect((html.match(/<span class="character-rarity">★★★★<\/span>/g) ?? [])).toHaveLength(6)
    expect((html.match(/disabled=""/g) ?? [])).toHaveLength(0)
    expect(html).toContain('Actions d’Invocation')
    expect(html).toContain('Invocation x1')
    expect(html).toContain('Invocation x10')
    expect(html).not.toContain('Disponible en permanence')
    expect(html).not.toContain('<span>hydro</span>')
  })
  it('keeps the compact Home hero read-only without a Change control', () => {
    const html = renderToStaticMarkup(<BannerHero compact gacha={data(five[0]!.id)} onSetTarget={vi.fn()} onOpen={vi.fn()} />)
    expect(html).toContain('Five 1')
    expect(html).toContain('home-banner-hit-area')
    expect(html).toContain('Ouvrir l’écran Invocation')
    expect(html).not.toContain('banner-change-button')
    expect(html).not.toContain('>Changer<')
    expect((html.match(/disabled=""/g) ?? [])).toHaveLength(2)
  })

  it('freezes pull and target controls while a request survives an Invocation remount', () => {
    const html = renderToStaticMarkup(<BannerHero gacha={data(five[0]!.id)} onSetTarget={vi.fn()} onPull={vi.fn()} pendingPullCount={10} showDetails />)

    expect((html.match(/disabled=""/g) ?? [])).toHaveLength(3)
    expect(html).toMatch(/class="banner-change-button" disabled="">Changer<\/button>/)
    expect(html).toContain('Invocation x1')
    expect(html).toContain('Invocation…')

    const availableHtml = renderToStaticMarkup(<BannerHero gacha={data(five[0]!.id)} onSetTarget={vi.fn()} onPull={vi.fn()} pendingPullCount={null} showDetails />)
    expect((availableHtml.match(/disabled=""/g) ?? [])).toHaveLength(0)
    expect(availableHtml).toMatch(/class="banner-change-button">Changer<\/button>/)
  })

  it('prevents every target choice while a Pull request is pending', () => {
    const onSetTarget = vi.fn()
    const html = renderToStaticMarkup(<BannerHero gacha={data(null)} onSetTarget={onSetTarget} pendingPullCount={10} />)

    expect((html.match(/character-showcase-gacha/g) ?? [])).toHaveLength(4)
    expect((html.match(/disabled=""/g) ?? [])).toHaveLength(4)
    expect(onSetTarget).not.toHaveBeenCalled()
  })

  it('keeps the compact no-target preview passive and navigable', () => {
    const html = renderToStaticMarkup(<BannerHero compact gacha={data(null)} onSetTarget={vi.fn()} onOpen={vi.fn()} />)
    expect((html.match(/character-showcase-gacha/g) ?? [])).toHaveLength(4)
    expect((html.match(/disabled=""/g) ?? [])).toHaveLength(4)
    expect(html).toContain('home-banner-hit-area')
    expect(html).not.toContain('featured-four-stars')
  })
});
