// R497: retained from the validated Ami legacy catalogue; no transport is added.
export const friendshipPhrases = [
  "leur amitié s’embellit doucement.",
  "un petit lien magique brille entre eux.",
  "leur complicité gagne une étincelle.",
  "une douce lumière entoure leur amitié.",
  "leur lien devient encore plus précieux.",
  "un sourire traverse leur aventure.",
  "leur amitié fleurit comme un jardin secret.",
  "une pluie d’étoiles accompagne ce geste.",
  "leur duo gagne un peu plus de magie.",
  "une belle énergie les rapproche.",
  "leur lien scintille.",
  "un moment tout doux vient d’être partagé.",
  "leur amitié gagne une nouvelle couleur.",
  "des petites étoiles dansent autour d’eux.",
  "leur complicité devient encore plus lumineuse.",
  "un joli souvenir vient de naître.",
  "leur amitié rayonne un peu plus fort.",
  "une vague de douceur traverse le stream.",
  "leur lien prend une jolie forme brillante.",
  "un cœur de plus bat dans leur aventure.",
  "la magie de l’amitié fait son effet.",
  "leur complicité se couvre de paillettes.",
  "un petit miracle d’amitié apparaît.",
  "leur relation gagne une note sucrée.",
  "le monde sent leur amitié grandir.",
  "leurs cœurs brillent en rythme.",
  "une étincelle tendre les accompagne.",
  "leur amitié devient encore plus adorable.",
  "une petite constellation naît entre eux.",
  "leur lien se renforce dans la bonne humeur.",
  "un rayon de tendresse passe par ici.",
  "leur aventure commune gagne des paillettes.",
  "une douce vibration d’amitié se répand.",
  "leur complicité fait fondre tout le monde.",
  "les étoiles valident cette amitié.",
  "leur amitié reçoit une bénédiction sucrée.",
  "un nuage de tendresse les entoure.",
  "leur duo devient encore plus attachant.",
  "un joli éclat traverse leur lien.",
  "leur amitié gagne un bonus de douceur.",
  "une petite lumière s’allume entre eux.",
  "leur lien devient plus chaleureux.",
  "les paillettes ont choisi leur camp.",
  "leur amitié avance avec le sourire.",
  "un câlin cosmique traverse le stream.",
  "leur complicité brille comme jamais.",
  "un petit souffle magique les rapproche.",
  "leur amitié prend un niveau de mignonnerie.",
  "les cœurs font la fête autour d’eux.",
  "leur lien devient une vraie petite légende.",
] as const;
