import type { NavigationMenuDestinationId, NavigationMenuPreferenceDto } from '../api/types'
import type { ScreenId } from '../types'

export type MainNavigationId = 'home' | 'invocation' | 'characters' | 'activities' | 'inventory' | 'shop' | 'configuration'
export type NavigationDestination = Readonly<{ id: NavigationMenuDestinationId; label: string; icon: string; screen: ScreenId | null; available: boolean }>
export const mainNavigation = [{ id: 'home', label: 'Accueil', icon: '⌂' }, { id: 'invocation', label: 'Invocation', icon: '✦' }, { id: 'characters', label: 'Personnages', icon: '♙' }, { id: 'activities', label: 'Activités', icon: '◫' }, { id: 'inventory', label: 'Sac', icon: '◇' }, { id: 'shop', label: 'Boutique', icon: '♢' }, { id: 'configuration', label: 'Configuration', icon: '⚙' }] as const
export const characterTabs = [{ screen: 'characters-box', label: 'Box' }, { screen: 'characters-team', label: 'Équipe' }, { screen: 'characters-catalog', label: 'Catalogue' }] as const
export const activityTabs = [{ screen: 'activities-dailies', label: 'Quotidiennes' }, { screen: 'activities-missions', label: 'Missions' }, { screen: 'activities-combat', label: 'Combat' }, { screen: 'activities-event', label: 'Événement' }, { screen: 'activities-contest', label: 'Concours' }] as const
export const navigationDestinations: readonly NavigationDestination[] = [
  { id: 'home', label: 'Accueil', icon: '⌂', screen: 'home', available: true }, { id: 'invocation', label: 'Invocation', icon: '✦', screen: 'invocation', available: true },
  { id: 'box', label: 'Box', icon: '▦', screen: 'characters-box', available: true }, { id: 'team', label: 'Équipe', icon: '♟', screen: 'characters-team', available: true }, { id: 'catalog', label: 'Catalogue', icon: '♙', screen: 'characters-catalog', available: true },
  { id: 'dailies', label: 'Quotidiennes', icon: '☼', screen: 'activities-dailies', available: true }, { id: 'missions', label: 'Missions', icon: '▤', screen: 'activities-missions', available: true }, { id: 'combat', label: 'Combat', icon: '⚔', screen: 'activities-combat', available: true }, { id: 'event', label: 'Événement', icon: '◈', screen: 'activities-event', available: true }, { id: 'contest', label: 'Concours', icon: '♜', screen: 'activities-contest', available: true },
  { id: 'inventory', label: 'Sac', icon: '◇', screen: 'inventory', available: true }, { id: 'shop', label: 'Boutique', icon: '♢', screen: 'shop', available: true }, { id: 'bank', label: 'Banque', icon: '●', screen: 'bank', available: true },
  { id: 'history', label: 'Historique', icon: '◷', screen: null, available: false }, { id: 'tutorial', label: 'Tutoriel', icon: '?', screen: null, available: false }, { id: 'configuration', label: 'Configuration', icon: '⚙', screen: 'configuration', available: true },
]
export const defaultNavigationPreference: NavigationMenuPreferenceDto = { version: 1, order: navigationDestinations.map(({ id }) => id), hidden: [] }
export function mainIdForScreen(screen: ScreenId): MainNavigationId | null { if (screen.startsWith('characters-')) return 'characters'; if (screen.startsWith('activities-')) return 'activities'; if (screen === 'bank' || screen === 'moderation') return null; return screen as MainNavigationId }
export function parseNavigationHash(hash: string): ScreenId { const value = hash.replace(/^#/, '').toLocaleLowerCase('fr-FR'); const routes: Record<string, ScreenId> = { home: 'home', invocation: 'invocation', box: 'characters-box', team: 'characters-team', characters: 'characters-catalog', 'characters/box': 'characters-box', 'characters/team': 'characters-team', 'characters/catalog': 'characters-catalog', activities: 'activities-dailies', 'activities/dailies': 'activities-dailies', 'activities/missions': 'activities-missions', 'activities/combat': 'activities-combat', 'activities/event': 'activities-event', 'activities/contest': 'activities-contest', inventory: 'inventory', shop: 'shop', bank: 'bank', configuration: 'configuration', moderation: 'moderation' }; return routes[value] ?? 'home' }
export function hashForScreen(screen: ScreenId) { const hashes: Record<ScreenId, string> = { home: 'home', invocation: 'invocation', 'characters-box': 'characters/box', 'characters-team': 'characters/team', 'characters-catalog': 'characters/catalog', 'activities-dailies': 'activities/dailies', 'activities-missions': 'activities/missions', 'activities-combat': 'activities/combat', 'activities-event': 'activities/event', 'activities-contest': 'activities/contest', inventory: 'inventory', shop: 'shop', bank: 'bank', configuration: 'configuration', moderation: 'moderation' }; return hashes[screen] }
